const names99 = [
  { arabic: "ٱلْرَّحْمَـانُ", transliteration: "Ar-Rahman", meaning: "The Most Merciful" },
  { arabic: "ٱلْرَّحِيْمُ", transliteration: "Ar-Raheem", meaning: "The Bestower of Mercy" },
  { arabic: "ٱلْمَلِكُ", transliteration: "Al-Malik", meaning: "The King" },
  { arabic: "ٱلْقُدُّوسُ", transliteration: "Al-Quddus", meaning: "The Most Sacred" },
  { arabic: "ٱلْسَّلَامُ", transliteration: "As-Salam", meaning: "The Perfection and Giver of Peace" },
  { arabic: "ٱلْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning: "The Giver of Security" },
  { arabic: "ٱلْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning: "The Guardian" },
  { arabic: "ٱلْعَزِيزُ", transliteration: "Al-Aziz", meaning: "The Almighty" },
  { arabic: "ٱلْجَبَّارُ", transliteration: "Al-Jabbar", meaning: "The Compeller" },
  { arabic: "ٱلْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: "The Supreme" },
  { arabic: "ٱلْخَالِقُ", transliteration: "Al-Khaliq", meaning: "The Creator" },
  { arabic: "ٱلْبَارِئُ", transliteration: "Al-Bari", meaning: "The Originator" },
  { arabic: "ٱلْمُصَوِّرُ", transliteration: "Al-Musawwir", meaning: "The Fashioner" },
  { arabic: "ٱلْغَفَّارُ", transliteration: "Al-Ghaffar", meaning: "The Constant Forgiver" },
  { arabic: "ٱلْقَهَّارُ", transliteration: "Al-Qahhar", meaning: "The Subduer" },
  { arabic: "ٱلْوَهَّابُ", transliteration: "Al-Wahhab", meaning: "The Bestower" },
  { arabic: "ٱلْرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning: "The Provider" },
  { arabic: "ٱلْفَتَّاحُ", transliteration: "Al-Fattah", meaning: "The Opener" },
  { arabic: "ٱلْعَلِيمُ", transliteration: "Al-Alim", meaning: "The All-Knowing" },
  { arabic: "ٱلْقَابِضُ", transliteration: "Al-Qabid", meaning: "The Withholder" },
  { arabic: "ٱلْبَاسِطُ", transliteration: "Al-Basit", meaning: "The Extender" },
  { arabic: "ٱلْخَافِضُ", transliteration: "Al-Khafid", meaning: "The Reducer" },
  { arabic: "ٱلْرَّافِعُ", transliteration: "Ar-Rafi", meaning: "The Exalter" },
  { arabic: "ٱلْمُعِزُّ", transliteration: "Al-Mu'izz", meaning: "The Honorer" },
  { arabic: "ٱلْمُذِلُّ", transliteration: "Al-Mudhill", meaning: "The Humiliator" },
  { arabic: "ٱلْسَّمِيعُ", transliteration: "As-Sami", meaning: "The All-Hearing" },
  { arabic: "ٱلْبَصِيرُ", transliteration: "Al-Basir", meaning: "The All-Seeing" },
  { arabic: "ٱلْحَكَمُ", transliteration: "Al-Hakam", meaning: "The Judge" },
  { arabic: "ٱلْعَدْلُ", transliteration: "Al-Adl", meaning: "The Just" },
  { arabic: "ٱلْلَّطِيفُ", transliteration: "Al-Latif", meaning: "The Subtle One" },
  { arabic: "ٱلْخَبِيرُ", transliteration: "Al-Khabir", meaning: "The Acquainted" },
  { arabic: "ٱلْحَلِيمُ", transliteration: "Al-Halim", meaning: "The Forbearing" },
  { arabic: "ٱلْعَظِيمُ", transliteration: "Al-Azim", meaning: "The Magnificent" },
  { arabic: "ٱلْغَفُورُ", transliteration: "Al-Ghafur", meaning: "The Forgiving" },
  { arabic: "ٱلْشَّكُورُ", transliteration: "Ash-Shakur", meaning: "The Appreciative" },
  { arabic: "ٱلْعَلِيُّ", transliteration: "Al-Ali", meaning: "The Most High" },
  { arabic: "ٱلْكَبِيرُ", transliteration: "Al-Kabir", meaning: "The Most Great" },
  { arabic: "ٱلْحَفِيظُ", transliteration: "Al-Hafiz", meaning: "The Preserver" },
  { arabic: "ٱلْمُقِيتُ", transliteration: "Al-Muqit", meaning: "The Sustainer" },
  { arabic: "ٱلْحَسِيبُ", transliteration: "Al-Hasib", meaning: "The Reckoner" },
  { arabic: "ٱلْجَلِيلُ", transliteration: "Al-Jalil", meaning: "The Majestic" },
  { arabic: "ٱلْكَرِيمُ", transliteration: "Al-Karim", meaning: "The Generous" },
  { arabic: "ٱلْرَّقِيبُ", transliteration: "Ar-Raqib", meaning: "The Watchful" },
  { arabic: "ٱلْمُجِيبُ", transliteration: "Al-Mujib", meaning: "The Responsive" },
  { arabic: "ٱلْوَاسِعُ", transliteration: "Al-Wasi", meaning: "The All-Encompassing" },
  { arabic: "ٱلْحَكِيمُ", transliteration: "Al-Hakim", meaning: "The Wise" },
  { arabic: "ٱلْوَدُودُ", transliteration: "Al-Wadud", meaning: "The Loving" },
  { arabic: "ٱلْمَجِيدُ", transliteration: "Al-Majid", meaning: "The Glorious" },
  { arabic: "ٱلْبَاعِثُ", transliteration: "Al-Ba'ith", meaning: "The Resurrector" },
  { arabic: "ٱلْشَّهِيدُ", transliteration: "Ash-Shahid", meaning: "The Witness" },
  { arabic: "ٱلْحَقُّ", transliteration: "Al-Haqq", meaning: "The Truth" },
  { arabic: "ٱلْوَكِيلُ", transliteration: "Al-Wakil", meaning: "The Trustee" },
  { arabic: "ٱلْقَوِيُّ", transliteration: "Al-Qawi", meaning: "The Strong" },
  { arabic: "ٱلْمَتِينُ", transliteration: "Al-Matin", meaning: "The Firm" },
  { arabic: "ٱلْوَلِيُّ", transliteration: "Al-Wali", meaning: "The Protecting Friend" },
  { arabic: "ٱلْحَمِيدُ", transliteration: "Al-Hamid", meaning: "The Praiseworthy" },
  { arabic: "ٱلْمُحْصِيُ", transliteration: "Al-Muhsi", meaning: "The Accounter" },
  { arabic: "ٱلْمُبْدِئُ", transliteration: "Al-Mubdi", meaning: "The Originator" },
  { arabic: "ٱلْمُعِيدُ", transliteration: "Al-Mu'id", meaning: "The Restorer" },
  { arabic: "ٱلْمُحْيِي", transliteration: "Al-Muhyi", meaning: "The Giver of Life" },
  { arabic: "ٱلْمُمِيتُ", transliteration: "Al-Mumit", meaning: "The Creator of Death" },
  { arabic: "ٱلْحَيُّ", transliteration: "Al-Hayy", meaning: "The Ever-Living" },
  { arabic: "ٱلْقَيُّومُ", transliteration: "Al-Qayyum", meaning: "The Self-Existing" },
  { arabic: "ٱلْوَاجِدُ", transliteration: "Al-Wajid", meaning: "The Finder" },
  { arabic: "ٱلْمَاجِدُ", transliteration: "Al-Majid", meaning: "The Noble" },
  { arabic: "ٱلْوَاحِدُ", transliteration: "Al-Wahid", meaning: "The One" },
  { arabic: "ٱلْأَحَدُ", transliteration: "Al-Ahad", meaning: "The Unique" },
  { arabic: "ٱلْصَّمَدُ", transliteration: "As-Samad", meaning: "The Eternal" },
  { arabic: "ٱلْقَادِرُ", transliteration: "Al-Qadir", meaning: "The Capable" },
  { arabic: "ٱلْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: "The Powerful" },
  { arabic: "ٱلْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: "The Expediter" },
  { arabic: "ٱلْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer" },
  { arabic: "ٱلْأَوَّلُ", transliteration: "Al-Awwal", meaning: "The First" },
  { arabic: "ٱلْآخِرُ", transliteration: "Al-Akhir", meaning: "The Last" },
  { arabic: "ٱلْظَّاهِرُ", transliteration: "Az-Zahir", meaning: "The Manifest" },
  { arabic: "ٱلْبَاطِنُ", transliteration: "Al-Batin", meaning: "The Hidden" },
  { arabic: "ٱلْوَالِي", transliteration: "Al-Wali", meaning: "The Governor" },
  { arabic: "ٱلْمُتَعَالِي", transliteration: "Al-Muta'ali", meaning: "The Most Exalted" },
  { arabic: "ٱلْبَرُّ", transliteration: "Al-Barr", meaning: "The Source of Goodness" },
  { arabic: "ٱلْتَّوَّابُ", transliteration: "At-Tawwab", meaning: "The Acceptor of Repentance" },
  { arabic: "ٱلْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning: "The Avenger" },
  { arabic: "ٱلْعَفُوُّ", transliteration: "Al-'Afuww", meaning: "The Pardoner" },
  { arabic: "ٱلْرَّؤُفُ", transliteration: "Ar-Ra'uf", meaning: "The Kind" },
  { arabic: "ٱلْمَالِكُ ٱلْمُلْكُ", transliteration: "Malik-ul-Mulk", meaning: "Master of the Kingdom" },
  { arabic: "ٱلْذُو ٱلْجَلَالِ وَٱلْإِكْرَامُ", transliteration: "Dhul-Jalali wal-Ikram", meaning: "Lord of Majesty and Generosity" },
  { arabic: "ٱلْمُقْسِطُ", transliteration: "Al-Muqsit", meaning: "The Equitable" },
  { arabic: "ٱلْجَامِعُ", transliteration: "Al-Jami", meaning: "The Gatherer" },
  { arabic: "ٱلْغَنيُّ", transliteration: "Al-Ghani", meaning: "The Self-Sufficient" },
  { arabic: "ٱلْمُغْنِيُ", transliteration: "Al-Mughni", meaning: "The Enricher" },
  { arabic: "ٱلْمَانِعُ", transliteration: "Al-Mani", meaning: "The Preventer" },
  { arabic: "ٱلْضَّارُ", transliteration: "Ad-Darr", meaning: "The Distresser" },
  { arabic: "ٱلْنَّافِعُ", transliteration: "An-Nafi", meaning: "The Benefactor" },
  { arabic: "ٱلْنُّورُ", transliteration: "An-Nur", meaning: "The Light" },
  { arabic: "ٱلْهَادِي", transliteration: "Al-Hadi", meaning: "The Guide" },
  { arabic: "ٱلْبَدِيعُ", transliteration: "Al-Badi", meaning: "The Incomparable" },
  { arabic: "ٱلْبَاقِي", transliteration: "Al-Baqi", meaning: "The Everlasting" },
  { arabic: "ٱلْوَارِثُ", transliteration: "Al-Warith", meaning: "The Inheritor" },
  { arabic: "ٱلْرَّشِيدُ", transliteration: "Ar-Rashid", meaning: "The Righteous Guide" },
  { arabic: "ٱلْصَّبُورُ", transliteration: "As-Sabur", meaning: "The Patient" }
];

export function initNames() {
  const grid = document.getElementById('names-grid');

  names99.forEach((name) => {
    const card = document.createElement('div');
    card.className = 'name-card';
    card.innerHTML = `
      <div class="name-arabic">${name.arabic}</div>
      <div class="name-transliteration">${name.transliteration}</div>
      <div class="name-meaning">${name.meaning}</div>
    `;
    grid.appendChild(card);
  });
}
